import React from 'react'
import Moment from 'moment'

const UyelikSozlesmesi = () => {
    return (
        <div>
            <p>TARAFLAR</p>
            <p>Hizmet Sağlayıcı Bilgileri (Sözleşmede “ENBİOSİS olarak anılacaktır.)</p>
            <p>Hizmet Sağlayıcı           :ENBİOSİS BİYOTEKNOLOJİ ANONİM ŞİRKETİ</p>
            <p>Adres                              : MASLAK MAH. TASYONCASI SK. MASLAK 1453 1U T4A T4B
                NO: 1 U IÇ KAPI NO: B91 SARIYER/ ISTANBUL
            </p>
            <p>Ticaret Sicil Numarası :206241-5</p>
            <p>Mersis numarası          :0334097043200001 </p>
            <p>Telefon                           : +90 212 809 30 77</p>
            <p>Faks                                : +90 212 803 05 60</p>
            <p>Web Adresi                   :www.Enbiosis.com</p>
            <p>E-Posta                           : info@Enbiosis.com</p>
            <p>Üye Bilgileri (Sözleşmede “Üye” olarak anılacaktır.)</p>
            <p>Üye’ninAdı ve Soyadı           :</p>
            <p>Adresi                                      :</p>
            <p>Telefon                                   :</p>
            <p>E-posta                                   :</p>
            <p>KONU</p>
            <p>İşbu üyelik sözleşmesinin (“Sözleşme“) konusu, üyenin yazılı veya elektronik ortamda işbu sözleşmeyi onaylayarak ve toplam üyelik ücretini ödeyerek ENBİOSİS’ten yararlanması ve ENBİOSİS’in kullanması ile ilgili olarak tarafların hak ve yükümlülüklerini belirlemektir</p>
            <p>TANIMLAR</p>
            <p>ENBİOSİS: Üyenin internet sitesi üzerinden elektronik ortamda işbu sözleşmeyi onayladıktan ve toplam kullanım ücretini ödedikten sonra kullanıcı adı ve şifre oluşturarak faydalanmaya başladığı Internet Explorer, Google Chrome ve MozillaFirefox ve benzeri internet tarayıcıları ve aktif internet bağlantısı üzerinden çalıştırılabilen yapay zeka teknolojileri başta olmak üzere sair teknolojikler kullanarak müşterilerinin sağlıklı yaşam ihtiyaçlarına yönelik kişiselleştirilmiş beslenme çözüm ve önerileri ve kişiselleştirilmiş diyet önerilerini sunan ticari oluşumu ifade eder.</p>
            <p>Tüketici: 6502 sayılı Tüketicinin Korunması Hakkında Kanun Madde 3 uyarınca ticari veya mesleki olmayan amaçlarla hareket eden gerçek ve tüzel kişi üyeyi ifade eder.</p>
            <p>Gizlilik Politikası: <a href="https://www.enbiosis.com/gizlilik-politikasi" target="_blank" rel="noopener noreferrer">https://www.enbiosis.com/gizlilik-politikasi</a> adresinde yer alan gizlilik koşullarını ifade eder.</p>
            <p>İnternet Sitesi: <a href="https://www.enbiosis.com/" target="_blank" rel="noopener noreferrer">https://www.enbiosis.com/</a> websitesini ifade eder.</p>
            <p>Kullanım Koşulları: <a href="https://www.enbiosis.com/kullanim-kosullari" target="_blank" rel="noopener noreferrer">https://www.enbiosis.com/kullanim-kosullari</a> adresinde yer alan kullanım koşullarını ifade eder.</p>
            <p>Ön Bilgilendirme Formu: TKHK ve 27 Kasım 2014 tarihli ve 29188 sayılı ResmiGazete’de yayımlanan Mesafeli Sözleşmeler Yönetmeliği uyarınca, üye tarafından toplam kullanım ücreti ödemeden önce elektronik ortamda onaylanan belgeleri ifade eder.</p>
            <p>Taraf: ENBİOSİSile Üye’den her biri anlamına gelir; ENBİOSİS ile Üye topluca “Taraflar” olarak anılırlar</p>
            <p>ÜYELİK SİSTEMİ VE ENBİOSİS KULLANIMI</p>
            <p>Üyenin ENBİOSİS’tenfaydalanabilmesi öncelikle işbu Sözleşme’nin ve ön bilgilendirme formunun internet sitesi üzerinden, elektronik ortamda onaylanmasına bağlıdır</p>
            <p>ENBİOSİS’te bulunan tüm içerik resmi ve özel kaynaklardan edinilmektedir. Üye,sağlayıcının ENBİOSİS’in içeriğinin doğruluğu ve güncelliği için gerekli bütün çabayı gösterdiğini ancak sağlayıcının yer alan içerikten hiçbir şekilde sorumlu olmadığını kabul ve beyan eder. Sağlayıcı, kendi kontrolünde olmayan üçüncü kişilerin işlettiği internet sitelerine ve/veya portallara, dosyalara veya içeriklere uzantı (ya da link) verebilir. Bu uzantılar, ilgili internet sitesini veya siteyi işleten kişiyi desteklemek amacı veya internet sitesine ya da içerdiği bilgilere yönelik herhangi bir açık veya gizli beyan veya garanti niteliği taşımamaktadır. ENBİOSİSüzerindeki uzantılar aracılığıyla erişilen internet siteleri, dosyalar ve içerikler, internet sitelerinden sunulan hizmetler, ürünler ya da bunların içeriği hakkında ENBİOSİS’inhiçbir sorumluluğu bulunmamaktadır.</p>
            <p>Üye, ENBİOSİS’i oluşturan tüm yazılımların genel itibarıyla hatasız olmadığını ve işbu sözleşmede ENBİOSİS tarafından portala ya da sisteme veya yazılımlara dair hiçbir beyan ve tekeffül verilmediğini bildiğini kabul ve beyan eder.</p>
            <p>Üye, üyelik sistemi üzerinden üye olurken vermiş olduğu tüm bilgilerin doğru ve tam olduğunu ve yanıltıcı olmadığını, bunların yanlış, eksik veya yanıltıcı olmasından kaynaklanabilecek her türlü zarardan ve yaptırımdan münhasıran sorumlu olduğunu, ENBİOSİS’in bu yönde uğrayabileceği doğrudan, dolaylı ve her türlü zararı nakden ve derhal tazmin edeceğini kabul, beyan ve taahhüt eder. Üye, kendisi tarafından belirlenen ve kendisine münhasır kullanıcı adı ve şifrenin gizliliğinden sorumlu olduğunu, bunların kendi kusuru veya ihmali neticesinde üçüncü kişilerin eline geçmesi ve/veya bu sebeple uğrayabileceği her türlü zarar dolayısıyla ENBİOSİS’in herhangi bir sorumluluğu olmadığını kabul, beyan ve taahhüt eder.</p>
            <p>Üyenin ENBİOSİS’ten faydalanabilmesi için gerekli olan kullanıcı adı ve şifre kişiye özeldir. Bu doğrultuda, üye, kendisine tahsis edilen kullanıcı adı ve şifre aracılığıyla ENBİOSİS’in yalnızca kendisi tarafından kullanılacağını kabul, beyan ve taahhüt eder. Üyenin kullanıcı adının ve şifresinin üye dışındaki üçüncü kişilerce kullanıldığının tespit edilmesi halinde, üyelik derhal iptal edilir ve ENBİOSİS’inkullanımı ilgili üyenin kullanımına kapatılır.</p>
            <p>Üye, ENBİOSİS üzerinden yapacağı çevrimiçi ödeme yöntemleri, kredi kartı ya da banka kartı kullanımı gerektiren işlemlerde kredi kartı veya banka kartı malikinin rızası ve bilgisi dahilinde işlem yapacağını; aksi takdirde ödeme iadesi, hizmeti ifa etmeme veya benzeri sebeplerden kaynaklanabilecek, avukatlık masrafları da dâhil olmak üzere her türlü masraflardan ve zarardan münhasıran sorumlu olacağını ve ENBİOSİS’ı bunlardan kaynaklanabilecek her türlü talepten âri tutacağını kabul, beyan ve taahhüt eder.</p>
            <p>Üye, ENBİOSİS tarafından kendisine işbu Sözleşme konusu ile ilgili olarak gönderilecek her türlü ticarî elektronik iletilere onay vermektedir. Bu kapsamda üye, ENBİOSİS tarafından kendisine, kişi müdahalesi olmadan çalışan faks, elektronik posta, kısa mesaj gibi otomatik arama sistemleri vasıtasıyla ya da başkaca iletişim vasıtaları ile üyeden işbu madde kapsamında alınan açık ve yazılı rızayauygun olarak herhangi bir izin alınmaksızın bilgilendirme, pazarlama veya reklam amacıyla her türlü elektronik ileti, kısa mesaj, faks vs. gönderilebileceğini kabul ve beyan eder. Üyenin ilgili ticari elektronik iletileri almak istememesi durumunda, üye her zaman bu rızasını geri alabilir.</p>
            <p>ENBİOSİS kapsamında firma tarafından sağlanan hizmetler ile ilgili üyenin bir şikâyeti veya talebi bulunması halinde, üye, söz konusu talep ve şikâyetlerini info@ENBİOSİS.com e-posta adresi veya 0 212 809 30 77 telefon numarası aracılığıyla ENBİOSİS ‘e iletebilir.</p>
            <p>ÜYENİN BEYAN, TEKEFFÜL VE TAAHHÜTLERİ</p>
            <p>Üye, ENBİOSİS’i ziyaret etmekle veya kullanmakla ENBİOSİS’teyer alan içeriği, kullanım koşullarını,gizlilik politikasını ve işbu sözleşmedeki koşulları ve okuduğunu, anladığını ve bu koşullarla bağlı olduğunu; hem bu koşullara hem de yürürlükte bulunan tüm kanunlara, yönetmeliklere ve sair mevzuata uyacağını açıkça kabul, beyan ve taahhüt etmiş bulunmaktadır</p>
            <p>Üye, 18 yaşından büyük ve Türk Medeni Kanunu’na göre reşit olduğunu kabul, beyan ve tekeffül eder.</p>
            <p>ENBİOSİS’i oluşturan tüm yazılımlara ilişkin kaynak kodu, veri kodu, yazılım ve sistem içerisindeki veri tabanı ve bunların geliştirilmiş versiyonları üzerindeki 5846 sayılı Fikir ve Sanat Eserleri Kanunu’nun 21. maddesinde “İşleme”, 22. maddesinde “Çoğaltma”, 23. Maddesinde “Yayma”, 24. maddesinde “Temsil” ve 25. maddesinde “İşaret Ses ve/veya Görüntü Nakline Yarayan Araçlarla Umuma İletim” hakları adı altında düzenlenen mali hakların tamamı üzerinde ve aynı kanunun 14. maddesinde “Umuma Arz Salahiyeti”, 15. maddesinde “Adın Belirtilmesi Salahiyeti” ve 16. maddesinde “Eserde Değişiklik Yapılmasını Men Etme” adı altında düzenlenen manevi hakları kullanma yetkisi dahil olmak ancak bunlarla sınırlı olmamak üzere tüm fikri mülkiyet hakları (telif hakkı ve sair hak) yer, süre, içerik, mecra ve sayı sınırı olmaksızın, münhasıran ENBİOSİS’eaittir ve ENBİOSİS’inyazılı ve açık onayı olmadan kopyalanamaz, tamamı ya da bir kısmı üzerinde işleme veya tersine mühendislik yapılamaz; asıl ve/veya işlenecek halinin/ tamamını veya bir kısmını doğrudan veya dolaylı olarak çoğaltılamaz; herhangi bir şekil veya yöntemle yayılamaz; doğrudan doğruya veya işaret, ses veya resim nakline yarayan araçlarla umumî mahallerde temsil suretiyle faydalanılamaz; dijital ortamlarda ve/ veya mobil araçlarla kullanılamaz, umuma iletilemez ve üçüncü kişilerin erişimine sunulamaz; Sözleşme tarihinde bilinen ve sözleşme tarihinden sonra geliştirilecek teknik olanaklarla üretilecek veri taşımaya yarayan araçlara kaydedilemez; her türlü görsel-işitsel eser içerisinde kullanılamaz ve sözleşme tarihinde bilinen veya ileride geliştirilecek yöntemlerle, işaret-ses ve/veya görüntü nakline yarayan araçlarla veya yeniden yayınlanmak suretiyle umuma iletilemez, sergilenemez, değiştirilemez, uyarlanamaz ya da tercüme edilemez. Üyeler, yalnızca ticari ve mesleki faaliyetleri kapsamında ENBİOSİS’inveri tabanında yer alan eser niteliğini haiz olsun olmasın sair kaynaktan atıf sureti ile yararlanabilirler ve bunları bir ticari amaç olmaksızın çoğaltabilirler. Bunların tamamının yahut bir kısmının Hukuk Bilgi Sistemi’nden çekilerek herhangi bir sistem oluşturulması, kitap haline getirilmesi, derlenmesi, üçüncü kişilere ücret karşılığı satışı kesinlikle yasaktır.</p>
            <p>Üye’nin işbu madde 5.3’e aykırı davrandığınınENBİOSİS’in takdirine bağlı olarak tespit edilmesi halinde, ENBİOSİS,Üye’nin Hukuk Bilgi Sistemi’ne erişimini derhal engelleyebilir. ENBİOSİS’in fikri haklar bakımından her türlü maddi ve manevi zararların tüm faiz ve fer’ilerin tahsili de dâhil olmak üzere her türlü hukuki ve cezai yola müracaat etme hakkı saklıdır.</p>
            <p>Üye, ENBİOSİS’in diğer üyelerine, herhangi bir ürünün ya da hizmetin istenmeyen iletilerini, reklamlarını veya davetlerini göndermemeyi kabul, beyan ve taahhüt eder. Ayrıca üye, ENBİOSİS üzerinden veya e-posta yoluyla ya da İnternet Sitesi dışında herhangi bir yolla yukarıda anılan kişilere ticari veya başka türlü e-postalar iletmek suretiyle teklifsiz e-posta göndermek, elektronik veya başka yollarla kullanıcı adlarını veya e-posta adreslerini toplamak da dâhil olmak üzere fakat bunlarla kısıtlı olmamak kaydıyla İnternet Sitesi’ni hiçbir şekilde hukuka aykırı şekilde, ENBİOSİS’in amaçlarından başka amaçlar için veya yetkisiz olarak kullanamaz.</p>
            <p>Üye, Spam, Virüs, Truva Atı ve bunlarla sınırlı olmaksızın benzeri diğer kötü niyetli yazılımlar ile İnternet Sitesi’nin çalışmasını durdurucu veya engelleyici iş, işlem veya eylemlerde bulunmayacağını veya bu yönde iş, işlem veya eylemlerde bulunan üçüncü kişilerle herhangi bir ilişki içerisinde olmayacağını kabul, beyan ve taahhüt eder.</p>
            <p>Üye, yegâne takdir yetkisi ENBİOSİS ‘te olmak üzere, İnternet Sitesi’ne erişim engellenmesine ilişkin mahkeme kararı ve ENBİOSİS ‘in kontrolünde olmayan teknik aksaklıklar dahil olmak üzere mücbir sebepler durumunda veya benzer sebeplerle herhangi bir zamanda, ENBİOSİS ‘inzaman zaman tüm hizmetlere veya hizmetlerin bir kısmına ya da İnternet Sitesi’ne erişimi tüm Üyeler için kısıtlayabileceğini kabul eder.</p>
            <p>Üye, kendisinin veya üçüncü kişilerin çıplak fotoğrafları, pornografik fotoğraflar veya görseller ve her türlü yasa dışı veya sosyal olarak kabul edilemez materyal dâhil olmak üzere fakat bunlarla kısıtlı olmamak kaydıyla; hiçbir şekilde onur kırıcı, iftira atıcı, saldırgan, fesada temayül eden, saygısız, ayıp, cinsel anlamda aşağılayıcı, tehdit edici, taciz edici, ırkçı veya yasa dışı materyal gönderemez, yayınlayamaz veya bunları hiçbir üyeye veya üye olmayan ENBİOSİS kullanıcılarına gösteremez. ENBİOSİS, bu türden materyalleri hiçbir bildirim yapmaksızın silme hakkını saklı tutar.</p>
            <p>İşbu Sözleşme, Sözleşme’nin onaylanması ve üyeye sistemi kullanabilmesi için gerekli olan erişim bilgilerinin iletilmesinden başlamak üzere akdedilmiştir. </p>
            <p>ENBİOSİS ‘in, üyenin işbu sözleşmede belirlenen yükümlülükleri yerine getirmemesi durumunda üyeye göndereceği bir ihtarname ile ihlalin on beş (15) gün içerisinde düzeltilmesini talep edecek, söz konusu süre neticesinde ihlalin düzeltilmemesi halinde ise dilediği takdirde işbu sözleşmeyi hiçbir tazminat sorumluluğuna tâbi olmaksızın feshetmek hakkını haiz olacaktır.</p>
            <p>Abonelik Sözleşmeleri Yönetmeliği Madde 22 uyarınca, üyenin ilgili maddedeki hakları saklıdır.</p>
            <p>Sözleşmenin herhangi bir sebeple feshedilmesi halinde, fesih bildiriminin hüküm ifade etmesinden itibaren 14 gün içinde üye tarafından ödenmiş olan kullanım ücretinin, üye tarafından kullanılmayan süre için tahsil edilmiş kısmı ENBİOSİS tarafından üyeye iade edilir.</p>
            <p>UYGULANACAK HUKUK, YETKİLİ MAHKEME VE DELİL SÖZLEŞMESİ</p>
            <p>İşbu Sözleşme, Türk Hukuku’na tâbidir.Taraflar arasında işbu Sözleşmeden doğabilecek ihtilafların hallinde İstanbul Merkez Mahkemeleri ve İcra Müdürlükleri yetkilidir. İşbu sözleşmeden kaynaklanabilecek ihtilaflarda, Gümrük ve Ticaret Bakanlığınca ilân edilen değere kadar Tüketici Hakem Heyetleri, belirtilen değerin üstünde Tüketici Mahkemeleri; Tüketici Mahkemelerinin bulunmadığı yerlerde Asliye Hukuk Mahkemeleri yetkilidir.</p>
            <p>İşbu Sözleşme’nin Tarafları, bu Sözleşme ve uygulanmasıyla ilgili olarak aralarında çıkabilecek her türlü uyuşmazlıkların çözümlenmesinde; Tarafların defter, kayıt ve belgeleri ile ENBİOSİS ‘inses kayıtlarının, Üye tarafından ENBİOSİS ‘e gönderilecek yazılı veya faks talimatlarının 6100 sayılı Hukuk Muhakemeleri Kanunu’nun 193. maddesi gereği münhasır delil olacağını, herhangi bir hususun ispatı için birbirlerine yemin teklif etmeyeceklerini kabul ve beyan ederler.</p>
            <p>İşbu Sözleşme Taraflar arasında {Moment().format('DD-MM-YYYY')} tarihinde akdedilmiştir.</p>
        </div>
    )
}

export default UyelikSozlesmesi;